drop --user on pip install dns plugin
NginxProxyManager/nginx-proxy-manager pull request #2971
Opened 2023-06-01 18:06 UTC by wolviex

Do not install dns_plugin (via pip) into the user site because it will lack sys.path precedence to urllib3 in /opt/certbot/lib/python3.7/site-packages.
resolves #2921 and #2844
solution recommended by certbot engineer: [https://community.letsencrypt.org/t/nginx-proxy-manager-and-cert/198147](https://community.letsencrypt.org/t/nginx-proxy-manager-and-cert/198147)
Tested with docker image 'jc21/nginx-proxy-manager:latest', Godaddy DNS API credentials and wildcard certificate.

2023-06-08 02:39 UTC, biggen1684 commented
Can confirm this patch fixes issues with DNS validation of SSLs through Godaddy. Should definitely be merged with the main branch,

2023-06-11 12:43 UTC, martindur commented
Worked smoothly with Route53 as well. Thanks for the effort @wolviex :pray:

2023-06-14 15:15 UTC, justSem commented
Your proposed fix does seem to throw some issues with the TransIP API
This error also occurs on a clean install.

```
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-5" --agree-tos --email "redacted@domain.tls" --domains "*.domain.tls" --authenticator dns-transip --dns-transip-credentials "/etc/letsencrypt/credentials/credentials-5"
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in 
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in 
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 21, in 
    import josepy as jose
  File "/opt/certbot/lib/python3.7/site-packages/josepy/__init__.py", line 40, in 
    from josepy.json_util import (
  File "/opt/certbot/lib/python3.7/site-packages/josepy/json_util.py", line 14, in 
    from OpenSSL import crypto
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in 
    from OpenSSL import crypto, SSL
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1517, in 
    class X509StoreFlags(object):
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

2023-06-14 15:22 UTC, wolviex commented
> Your proposed fix does seem to throw some issues with the TransIP API This error also occurs on a clean install.

Are you saying you get this same error on an fresh container pulled with the 'jc21/nginx-proxy-manager:latest' image tag?
OR are you saying this PR introduces the error not found on the latest?

2023-06-14 15:26 UTC, justSem commented
> > Your proposed fix does seem to throw some issues with the TransIP API This error also occurs on a clean install.
> 
> Are you saying you get this same error on an fresh container pulled with the 'jc21/nginx-proxy-manager:latest' image tag? OR are you saying this PR introduces the error not found on the latest?

Good point. I may have spoken a bit to soon.
But no, this error is not introduced by your PR, it just came apparent when testing your proposed solution.

When manualy applying the PR to the `:latest` container this error is present as well.

2023-06-15 05:41 UTC, unixorn commented
I was having the `sys.path precedence to urllib3` problem with Route 53 and this fixes it.

2023-06-16 16:29 UTC, wolviex commented
Appears to resolve #2844 as well

2023-06-20 09:44 UTC, justSem requested changes
Since I can't push to your PR branch; I'd propose the line

```javascript
const prepareCmd = '. /opt/certbot/bin/activate && pip install --no-cache-dir ' + dns_plugin.package_name + (dns_plugin.version_requirement || '') + ' ' + dns_plugin.dependencies + ' && deactivate';
```

to be changed to


```javascript
const prepareCmd = '. /opt/certbot/bin/activate && pip install --upgrade pyopenssl  && pip install --no-cache-dir ' + dns_plugin.package_name + (dns_plugin.version_requirement || '') + ' ' + dns_plugin.dependencies + ' && deactivate';
```

2023-06-23 04:54 UTC, wolviex reviewed
This PR directly addresses the error ```Will not install to user site``` and nothing else.
This is as recommended by a certbot engineer.

Please explain why the pyopenssl upgrade is to be considered a part of this PR.

2023-06-23 10:45 UTC, justSem commented
> This PR directly addresses the error `Will not install to user site` and nothing else. This is as recommended by a certbot engineer.
> 
> Please explain why the pyopenssl upgrade is to be considered a part of this PR.

I figured, since it fixes a subsequent issue, it might as well be integrated into the same PR. But if you wish, I'll create a separate PR for it.

2023-06-23 20:42 UTC, wolviex commented
> I figured, since it fixes a subsequent issue, it might as well be integrated into the same PR. But if you wish, I'll create a separate PR for it.

I thought you clarified that your issue is also present on the :latest ? 
It seems like a dependancy issue, due to deprecated functionality in pyopenssl
https://github.com/pyca/pyopenssl/issues/1142

It may be something that should be addressed in another module

2023-06-26 11:49 UTC, biggen1684 commented
Crazy that this PR hasn't been merged yet with the official since it clearly fixes an issue. @jc21 still around?

2023-06-27 23:27 UTC, wolviex commented
> Crazy that this PR hasn't been merged yet with the official since it clearly fixes an issue. @jc21 still around?

My Guess is this is backburner since it looks like a v3 based in golang is in the works.
BTW, this is the same fix process as already merged in commit 05307aa

2023-07-11 16:00 UTC, wolviex commented
> @wolviex I still need your version, so I guess it is still not fixed in latest with [05307aa](https://github.com/NginxProxyManager/nginx-proxy-manager/commit/05307aa253c073cf94237fc96d816ec2919f4d7f)

Sorry for the confusion - no, the issue is not fixed in 05307aa. I only meant it is the same fix **method** used in that commit, just for reference. 05307aa is also not latest (2a06384 is and my PR is on top of that).

2023-07-11 16:02 UTC, a1ad commented
Ok, no problem. I hope the PR is merging soon!

2023-07-20 02:20 UTC, jc21 commented
I'm almost happy to merge the PR, however I'd ask that someone (or more than one) test this image with PUID/PGID set and also test without it being set.

The certbot install stuff may behave differently when the process is run as a non-root user vs a root user.

2023-07-25 10:47 UTC, Nightreaver commented
I can confirm its working on AWS R53.
Have it running with 

```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:github-pr-2971'
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
```

and got my cert without issues

2023-07-25 15:23 UTC, mashb1t commented
tested and works for me too using Route53

2023-07-26 00:28 UTC, jc21 commented
I also only have Route53 in use for my hosts, but yeah I'd like to see other certbot plugins tested too.

2023-07-26 03:13 UTC, wolviex commented
I use GoDaddy, and have PUID/PGID set to 1000. This is what worked for me in the first place.
created new container without PUID/PGID and was still functional.
Note that I did have to workaround certbot-dns-godaddy issue with certbot/acme version mismatching by manually downgrading acme. I beleive this is unrelated.
[https://github.com/miigotu/certbot-dns-godaddy/issues/27](https://github.com/miigotu/certbot-dns-godaddy/issues/27)

2023-07-30 21:21 UTC, jc21 commented
Ok sounds good I'll merge it.

2023-07-30 21:21 UTC, merged